# vim:fileencoding=utf-8:foldmethod=marker

# my configs with Adwaita dark

#: Fonts {{{

 font_family      "FiraMono Nerd Font Mono"
 bold_font        auto
 italic_font      auto
 bold_italic_font auto
 font_size 10.0

#: }}}

#: Text cursor customization {{{

 cursor                    #deddda
 cursor_text_color         #1d1d20

 cursor_trail 500
 cursor_trail_decay 0.1 0.4
 cursor_trail_start_threshold 2

#: }}}

#: Scrollback {{{

 scrollback_pager_history_size 10

#: }}}

#: Mouse {{{

 mouse_hide_wait -3.0
 url_color                 #1a5fb4

#: Mouse actions {{{

#: }}}

#: }}}

#: Performance tuning {{{

#: }}}

#: Terminal bell {{{

 visual_bell_color         none

#: }}}

#: Window layout {{{

 remember_window_size  yes
 initial_window_width  800
 initial_window_height 400
 remember_window_position yes
 window_border_width 0.5pt
 window_padding_width 15

 active_border_color       #4f4f4f
 inactive_border_color     #282828
 bell_border_color         #ed333b

 hide_window_decorations no

 window_logo_path /$HOME/.config/tool-configs/logos/icons8-arch-linux-48.png
 window_logo_position bottom-right
 window_logo_alpha 0.5
 window_logo_scale 0

 #: }}}

#: Tab bar {{{

 tab_bar_edge top
 tab_bar_style powerline
 tab_bar_align left
 tab_bar_show_new_tab_button no
 tab_powerline_style round

 active_tab_foreground     #fcfcfc
 active_tab_background     #242424
 inactive_tab_foreground   #b0afac
 inactive_tab_background   #303030
 tab_bar_background        none
 tab_bar_margin_color      none

#: }}}

#: Color scheme {{{

 background                #1d1d20
 foreground                #deddda

 background_opacity 0.6
 background_blur 2

 selection_foreground      #c0bfbc
 selection_background      #303030


#: The color table {{{

 color0                    #1d1d20
 color1                    #ed333b
 color2                    #57e389
 color3                    #ff7800
 color4                    #62a0ea
 color5                    #9141ac
 color6                    #5bc8af
 color7                    #deddda

 color8                    #9a9996
 color9                    #f66151
 color10                   #8ff0a4
 color11                   #ffa348
 color12                   #99c1f1
 color13                   #dc8add
 color14                   #93ddc2
 color15                   #f6f5f4

#: }}}

#: Wide gamut color formats {{{

#: }}}

#: }}}

#: Advanced {{{

 shell fish
 editor neovim

#: }}}

#: OS specific tweaks {{{

wayland_titlebar_color    system
macos_titlebar_color      system

#: }}}

#: Keyboard shortcuts {{{

#: Clipboard {{{

#: }}}

#: Scrolling {{{

#: }}}

#: Window management {{{

#: }}}

#: Tab management {{{

#: }}}

#: Layout management {{{

#: }}}

#: Font sizes {{{

#: }}}

#: Select and act on visible text {{{

#: }}}

#: Miscellaneous {{{

#: }}}

#: }}}
